### ISSUE TITLE
New version crashes my game

### ISSUE THREAD

**Issue by Razor235T** [APeng215/FiltPick#11] opened 2024-08-29 08:53 UTC
FiltPick-forge-mc1.20.1-0.1.0
Minecraft 1.20.1
checked on both Forge 47.3.5 (with a lot of mods) and 47.3.7 (fresh install)

[latest.log](https://github.com/user-attachments/files/16796365/latest.log)

**Comment by APeng215** [comment] 2024-08-29 10:29
Thx for feedback. It's fixed in the latest release, ***FiltPick-forge-mc1.20.1-0.1.1***

**Comment by APeng215** [comment] 2024-08-29 10:42
I'm adding a note here for any modder who may encounter a similar issue in the future:

This issue is caused by the mixin config lacking the entry `"refmap": "mixins.filtpick.refmap.json"`.

### Solution

Just add one line `"refmap": "mixins.filtpick.refmap.json"` which should be corresponding to the one in `build.gradle` file.

Before:
```json
{
  "required": true,
  "minVersion": "0.8",
  "package": "net.apeng.filtpick.mixin",
  "compatibilityLevel": "JAVA_17",
  "mixins": [
    "ItemEntityMixin",
    "ServerPlayerEntityMixin"
  ],
  "client": [
    "InventoryScreenMixin"
  ],
  "injectors": {
    "defaultRequire": 1
  }
}

```
After: 
```json
{
  "refmap": "mixins.filtpick.refmap.json",
  "required": true,
  "minVersion": "0.8",
  "package": "net.apeng.filtpick.mixin",
  "compatibilityLevel": "JAVA_17",
  "mixins": [
    "ItemEntityMixin",
    "ServerPlayerEntityMixin"
  ],
  "client": [
    "InventoryScreenMixin"
  ],
  "injectors": {
    "defaultRequire": 1
  }
}

```

In `build.gradle` file:
```
mixin {
    // MixinGradle Settings
    add sourceSets.main, 'mixins.filtpick.refmap.json'
    config 'filtpick.mixins.json'
}
```

**Closed** 2024-08-30 06:15 UTC
